[idemp-pass][tests] Improve test framework

diff --git a/scripts/run-test b/scripts/run-test
--- a/scripts/run-test
+++ b/scripts/run-test
@@ -5,5 +5,12 @@ f="$1"
 # Convert the C file to .ll
 c-to-llvm "$f" "$f.ll" > /dev/null 2>&1
 
-# Run the pass on the .ll
-pass-apply -idemp -o "$f.pass.ll" "$f.ll"
+# The TEST_PASS_APPLY should point to a script that applies the correct form
+# of pass-apply
+if [[ -z "${TEST_PASS_APPLY}" ]]; then
+    echo "error: please export the TEST_PASS_APPLY command needed for this test"
+    exit 1
+fi
+
+# input - output
+${TEST_PASS_APPLY} "$f.ll" "$f.pass.ll"
diff --git a/scripts/run-testcase b/scripts/run-testcase
--- a/scripts/run-testcase
+++ b/scripts/run-testcase
@@ -22,6 +22,19 @@ expected=( $(grep -E -o '(\$.*$)' $f) )
 
 # Run the test case
 $SCRIPT_DIR/run-test "$f" > "$f.pass.txt" 2>&1
+result=$?
+
+#echo "$?"
+if [[ $result == 1 ]]; then
+    echo "run-test command failed, did you supply a TEST_PASS_APPLY variable?"
+    echo "TEST_PASS_APPLY=${TEST_PASS_APPLY}"
+    exit -1
+fi
+
+if [[ $result -gt 0 ]]; then
+    echo "run-test command failed, did the pass crash?"
+    exit -1
+fi
 
 for exp in ${expected[@]}; do
   if grep -Fxq -m1 "$exp" "$f.pass.txt" ; then
@@ -47,7 +60,7 @@ echo "==============================="
 echo "Tests passed: $passed_tests, failed: $failed_tests"
 
 if [ "$REMOVE_TMP_FILES" = true ] ; then
-  rm -f "$f.pass.ll" "$f.pass.txt" "$f.ll"
+  rm -f "$f.pass.ll" "*$f.ll" "$f.pass.txt" "$f.ll"
 fi
 
 exit $failed_tests
